# [CERT-MANAGER]: To enable cert-manager injection to webhooks set true
certmanager:
  enable: true

# [CONFIG]: Configuration for the controller-manager
config:
  backendDefault:
    serverImage: ghcr.io/kdex-tech/backend-static:0.1.5
    serverImagePullPolicy: IfNotPresent
  defaultImageRegistry: docker.io
  defaultNpmRegistry: registry.npmjs.org
  packages:
    packagerImage: ghcr.io/kdex-tech/cli-tools:0.3.9
    packagerImagePullPolicy: IfNotPresent
    toolsImage: ghcr.io/kdex-tech/node-tools:0.1.2
    toolsImagePullPolicy: IfNotPresent

# [MANAGER]: Manager Deployment Configurations
controllerManager:
  container:
    args:
    - "--leader-elect"
    - "--metrics-bind-address=:8443"
    - "--health-probe-bind-address=:8081"
    extraArgs: {}
      # x-foo:
      # - "--zap-log-level=info"
    extraEnv: {}
      # x-foo:
      # - name: FOO
      #   value: BAR
    image:
      repository: ghcr.io/kdex-tech/nexus-manager
      tag: ""
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8081
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8081
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - "ALL"
  replicas: 1
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 10

# These labels are applied to all resources in the chart
extraChartLabels: {}

# [METRICS]: Set to true to generate manifests for exporting metrics.
# To disable metrics export set false, and ensure that the
# ControllerManager argument "--metrics-bind-address=:8443" is removed.
metrics:
  enable: true

# [NETWORK POLICIES]: To enable NetworkPolicies set true
networkPolicy:
  enable: false

# [PROMETHEUS]: To enable a ServiceMonitor to export metrics to Prometheus set true
prometheus:
  enable: false

# [RBAC]: To enable RBAC (Permissions) configurations
rbac:
  enable: true

serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# [WEBHOOKS]: Webhooks configuration
# The following configuration is automatically generated from the manifests
# generated by controller-gen. To update run 'make manifests' and
# the edit command with the '--force' flag
webhook:
  enable: true
