package controller

import (
	"context"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	kdexv1alpha1 "kdex.dev/crds/api/v1alpha1"
)

var _ = Describe("KDexFunction Controller", func() {
	Context("When reconciling a KDexFunction", func() {
		const resourceName = "test-function"
		ctx := context.Background()

		AfterEach(func() {
			cleanupResources(namespace)
		})

		It("should fail if hostRef.name is empty", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-empty-hostref",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
				},
			}

			err := k8sClient.Create(ctx, resource)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("hostRef.name must not be empty"))
		})

		It("should fail if basePath does not match regex", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-invalid-basepath",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: "some-host"},
					API: kdexv1alpha1.API{
						BasePath: "/invalid", // only one segment, but regex is ^/\w+/\w+
						Paths: map[string]kdexv1alpha1.PathItem{
							"/invalid/test": {},
						},
					},
				},
			}

			err := k8sClient.Create(ctx, resource)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("match"))
		})

		It("should not create with invalid JSON OpenAPI", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: "some-host"},
					Metadata: &kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {
								Get: &runtime.RawExtension{
									Raw: []byte(`{`),
								},
							},
						},
					},
				},
			}

			err := k8sClient.Create(ctx, resource)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("json: error calling MarshalJSON for type *runtime.RawExtension: unexpected end of JSON input"))
		})
	})
})
