{{- if .Values.certmanager.enable }}
# Self-signed Issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "kcnas-operator.labels" . | nindent 4 }}
  name: {{ include "kcnas-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- if .Values.webhook.enable }}
---
# Certificate for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ include "kcnas-operator.fullname" . }}-serving
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcnas-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "kcnas-operator.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kcnas-operator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    - {{ include "kcnas-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
  issuerRef:
    kind: Issuer
    name: {{ include "kcnas-operator.fullname" . }}
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  secretName: {{ include "kcnas-operator.fullname" . }}-webhook-server
{{- end }}
{{- if .Values.metrics.enable }}
---
# Certificate for the metrics
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "kcnas-operator.labels" . | nindent 4 }}
  name: {{ include "kcnas-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ include "kcnas-operator.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kcnas-operator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    - {{ include "kcnas-operator.fullname" . }}-metrics.{{ .Release.Namespace }}.svc
  issuerRef:
    kind: Issuer
    name: {{ include "kcnas-operator.fullname" . }}
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  secretName: {{ include "kcnas-operator.fullname" . }}-metrics-server
{{- end }}
{{- end }}
