{{- if .Values.rbac.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if and .Values.controllerManager.serviceAccount .Values.controllerManager.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.controllerManager.serviceAccount.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "kcnas-operator.labels" . | nindent 4 }}
  name: {{ include "kcnas-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
