name: Publish Helm Chart
description: Publish Helm Chart to Github Container Registry (OCI)

runs:
  using: "composite"
  steps:
  - name: Install Helm
    shell: bash
    run: |
      curl -sL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash

  - name: Verify Helm Installation
    shell: bash
    run: |
      helm version

  - name: Setup Go
    uses: actions/setup-go@v6
    with:
      go-version-file: go.mod

  - name: Install Oras CLI
    shell: bash
    run: |
      VERSION="1.3.0"
      export GOOS=$(go env GOOS)
      export GOARCH=$(go env GOARCH)
      curl -sSL "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_${GOOS}_${GOARCH}.tar.gz" -o oras.tar.gz
      mkdir -p oras-install/
      tar -zxf oras.tar.gz -C oras-install/
      sudo chown root:0 oras-install/oras
      sudo mv oras-install/oras /usr/local/bin/
      rm -rf oras.tar.gz oras-install/

  - name: Verify Oras Installation
    shell: bash
    run: |
      oras version

  - name: Package the Helm Chart
    shell: bash
    run: |
      export CHART_VERSION=$(echo ${{ github.ref }} | sed -e 's,.*/v\(.*\),\1,')
      make copy-bundled-for-chart
      helm dependency update chart
      mkdir -p dist
      helm package --app-version ${CHART_VERSION} --version ${CHART_VERSION} -d dist chart

  - name: Log in to registry with Helm
    shell: bash
    run: |
      echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io/${{ github.repository }} --username ${{ github.actor }} --password-stdin

  - name: Log in to registry with Oras
    shell: bash
    run: |
      echo "${{ github.token }}" | oras login ghcr.io --username ${{ github.actor }} --password-stdin

  - name: Push Helm Charts to Github Container Registry (OCI)
    working-directory: dist
    shell: bash
    run: |
      CHART_VERSION=$(echo ${{ github.ref }} | sed -e 's,.*/v\(.*\),\1,')
      REGISTRY_URL="ghcr.io/${{ github.repository_owner }}/charts"
      OCI_URL="oci://$(echo "$REGISTRY_URL" | tr '[:upper:]' '[:lower:]')"
      for f in *.tgz ; do
          echo "$f"
          helm push "$f" "$OCI_URL"
          oras tag "${REGISTRY_URL}/host-manager:${CHART_VERSION}" latest
      done
  #
  # - name: Install YQ
  #   if: ${{ env.PUBLISH == 'true' }}
  #   shell: bash
  #   run: |
  #     curl -sLo ./yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
  #     chmod +x ./yq
  #     sudo mv ./yq /usr/local/bin/yq

  # - name: Test YQ Installation
  #   if: ${{ env.PUBLISH == 'true' }}
  #   shell: bash
  #   run: |
  #     yq --version

  # - name: Update and Publish the Helm Index
  #   if: ${{ env.PUBLISH == 'true' }}
  #   shell: bash
  #   run: |
  #     ./.github/scripts/publish_helm_index.sh
  #   env:
  #     GIT_REPOSITORY: ${{ github.repository }}
  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     INDEX_DIR: charts
  #     OWNER: ${{ github.actor }}
  #     PUBLISH_BRANCH: gh-pages
  #     REPO_URL: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
  #     REPOSITORY: ${{ github.event.repository.name }}

  # - name: Trigger Deploy GitHub Pages
  #   if: ${{ env.PUBLISH == 'true' }}
  #   shell: bash
  #   run: |
  #     ./.github/scripts/trigger_workflow.sh
  #   env:
  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     GIT_REPOSITORY: ${{ github.repository }}
  #     PUBLISH_BRANCH: gh-pages
  #     WORKFLOW_NAME: "Deploy GitHub Pages"
