apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "kcnas-operator.labels" . | nindent 4 }}
  name: {{ include "kcnas-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
