name: CI

on:
  push:
    branches-ignore:
    - "dependabot/**"
    paths:
    - "**"
    - "!docs/**"
    tags:
    - "v*"
  pull_request:
    paths:
    - "**"
    - "!docs/**"

defaults:
  run:
    shell: bash

permissions:
  packages: write
  contents: read

jobs:
  ci:
    name: Build, Test
    runs-on: ubuntu-latest
    steps:
    - name: Clone the code
      uses: actions/checkout@v6

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Run Linter
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.10.1

    - name: Run Unit Tests
      run: |
        go mod tidy
        make test

  test-chart:
    name: Test Chart
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Clone the code
      uses: actions/checkout@v6

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Install the latest version of kind
      run: |
        curl -sLo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Verify kind installation
      run: kind version

    - name: Create kind cluster
      run: kind create cluster

    - name: Run Go mod tidy
      run: |
        go mod tidy

    - name: Install kubectl
      run: |
        OS=$(go env GOOS)
        ARCH=$(go env GOARCH)
        VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
        echo "Downloading kubectl $VERSION for $OS/$ARCH..."
        curl -sLO "https://dl.k8s.io/release/$VERSION/bin/$OS/$ARCH/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        kubectl version --client

    - name: Install Helm
      run: |
        curl -sL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash

    - name: Verify Helm installation
      run: helm version

    - name: Lint Helm Chart
      run: |
        helm lint ./chart

    - name: Build and load nexus-manager image
      run: |
        make docker-build TAG=ci
        kind load docker-image kdex-tech/nexus-manager:ci

    - name: Install cert-manager via Helm
      run: |
        helm repo add jetstack https://charts.jetstack.io
        helm repo update
        helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set crds.enabled=true

    - name: Wait for cert-manager to be ready
      run: |
        kubectl wait --namespace cert-manager --for=condition=available --timeout=300s deployment/cert-manager
        kubectl wait --namespace cert-manager --for=condition=available --timeout=300s deployment/cert-manager-cainjector
        kubectl wait --namespace cert-manager --for=condition=available --timeout=300s deployment/cert-manager-webhook

    - name: Install the KDex CRDs
      run: |
        make install-crds

    - name: Install Helm chart for project
      run: |
        make copy-bundled-for-chart
        helm install kcnas-operator ./chart \
          --create-namespace \
          --namespace kcnas-operator \
          --set fullnameOverride=kcnas-operator \
          --set controllerManager.container.image.repository=kdex-tech/nexus-manager \
          --set controllerManager.container.image.tag=ci \
          --set controllerManager.container.imagePullPolicy=IfNotPresent

    - name: Check Helm release status
      run: |
        helm status kcnas-operator --namespace kcnas-operator

    - name: Verify controller manager is READY
      run: |
        kubectl -n kcnas-operator rollout status deployment kcnas-operator

    - name: Display the status of the bundled CRs
      run: |
        kubectl get kdex-c

  publish-image:
    name: Publish Docker Image
    needs: ci
    runs-on: ubuntu-latest
    if: (github.repository == 'kdex-tech/nexus-manager') && startsWith(github.ref, 'refs/tags/') && (github.event_name != 'pull_request')
    steps:
    - name: Clone the code
      uses: actions/checkout@v6

    - name: Publish Docker Image
      uses: ./.github/actions/publish-docker-image

  publish-chart:
    name: Publish Helm Chart
    needs: [publish-image, test-chart]
    runs-on: ubuntu-latest
    if: (github.repository == 'kdex-tech/nexus-manager') && startsWith(github.ref, 'refs/tags/') && (github.event_name != 'pull_request')
    steps:
    - name: Clone the code
      uses: actions/checkout@v6

    - name: Publish Helm Chart
      uses: ./.github/actions/publish-helm-chart
